---
functional:
  - Магазин должен быть реализован в виде SPA приложения, которое не перезагружает страницу
  - Сайт должен защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просмотра каталога товаров
  - В каталоге должно отображаться название товара
  - В каталоге должен отображаться рейтинг товара
  - В каталоге должна отображаться цена товара со скидкой
  - В каталоге должна отображаться цена товара без учета скидки
  - Товары в каталоге небходимо выводить постранично
  - Пользователь должен иметь возможность искать товары по категории
  - Пользователь должен иметь возможность искать товары по ключевому слову
  - Пользователь должен иметь возможность фильтровать товары по цене
  - Пользователь должен иметь возможность фильтровать товары по цвету
  - Пользователь должен иметь возможность фильтровать товары по размеру
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - На странице товара должно отображаться название товара
  - На странице товара должен отображаться рейтинг товара
  - На странице товара должна отображаться цена товара со скидкой
  - На странице товара должна отображаться цена товара без учета скидки
  - Пользователь должен иметь возможность добавить товар в корзину
  - Пользователь должен иметь возможность просматривать содержимое корзины
  - Пользователь должен иметь возможность удалить товар из корзины
  - Пользователь должен иметь возможность выйти из корзины и продолжить выбирать товары в каталоге
  - Пользователь должен иметь возможность оформить заказ в корзине
  - Пользователь должен иметь возможность перейти на страницу оплаты заказа после оформления
  - Корзина должна храниться в сессии браузера
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования
  - Веб-сайт должен быть разработан оптимизирован для скорости работы
  - Сайт должен быть безопасным
  - Сайт должен иметь адаптивную верстку, чтобы он был удобным на мобильных устройствах
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Для оформления заказа требуется регистрация
  - Для оформления заказа требуется авторизация
  - Пользователь должен иметь возможность оплатить товар
  - Пользователь должен иметь возможность оформить доставку товара
  - Пользователь должен иметь возможность просмотра списка заказов
  - Пользователь должен иметь возможность просмотра заказа
  - У сайта должна быть админка для добавления и редактирования товаров
