---
functional:
  - Пользователь должен иметь возможность просмотра каталога товаров
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность добавить товар в корзину
  - Пользователь должен иметь возможность просматривать содержимое корзины
  - Магазин должен быть реализован в виде SPA приложения, которое не перезагружает страницу
  - Каталог товаров небходимо выводить постранично
  - На странице товара должно отображаться название товара
  - На странице товара должен отображаться рейтинг товара
  - На странице товара должно отображаться цена товара со скидкой
  - На странице товара должно отображаться цена товара без учета скидки
  - Пользователь должен иметь возможность удалить товар из корзины
  - Пользователь должен иметь возможность выйти из корзины и продолжить выбирать товары в каталоге
  - Пользователь должен иметь возможность оформить заказ в корзине
  - Пользователь должен иметь возможность перейти на страницу оплаты заказа после оформления
  - Корзина должна храниться в сессии браузера
  - Сайт должен защищать данные пользователя
  - Пользователь должен иметь возможность искать товары по ключевому слову
  - Пользователь должен иметь возможность искать товары по категории
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования
  - Веб-сайт должен быть разработан оптимизирован для скорости работы
  - Сайт должен быть безопасным
  - Сайт должен иметь адаптивную верстку, чтобы он был удобным на мобильных устройствах
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Для оформления заказа требуется регистрация
  - Пользователь должен иметь возможность оплатить товар
  - Пользователь должен иметь возможность оформить доставку товара
